server:
  #  端口号
  port: 8088
  servlet:
    #    资源路径  注意：开头要有 '/'
    context-path: /myblog

spring:
  datasource:
    #    连接数据库
    url: jdbc:mysql://localhost:3306/i-blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #    使用阿里的druid连接池工作
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #      初始连接数
      initial-size: 2
      #      最大连接数
      max-active: 20
  jackson:
    #    全局设置使用jackson返回的json对象不包含null值
    default-property-inclusion: non_null

#    日志
logging:
  #  等级
  level:
    #    打印日志的范围
    com.sinsoled.myblog:
      #      trace：打印全部日志
      trace


mybatis:
  #  指定xml文件的位置
  mapper-locations: classpath:mapper/*.xml

accessOrigin: http://localhost:8080

#自定义的
jwt:
  secret: secret
  #token有效期2天
  expiration: 172800000
  #  expiration: 30000
  token: X-Token



